// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWvOhg0oJ5GtpJ8Ktdl0j42yIEwkTa7a8',
    appId: '1:952069462495:web:110c6a800e65898ebb8c6a',
    messagingSenderId: '952069462495',
    projectId: 'truecross-55cca',
    authDomain: 'truecross-55cca.firebaseapp.com',
    storageBucket: 'truecross-55cca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRMqgeQOFBQ0t3xqlh_OrBwUgJuvtY3o',
    appId: '1:952069462495:android:4f20cc150afaf922bb8c6a',
    messagingSenderId: '952069462495',
    projectId: 'truecross-55cca',
    storageBucket: 'truecross-55cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKcP6IxUseG1LXyqnxZFTpGz04RBB-r4',
    appId: '1:952069462495:ios:fedf971ab332704dbb8c6a',
    messagingSenderId: '952069462495',
    projectId: 'truecross-55cca',
    storageBucket: 'truecross-55cca.appspot.com',
    iosClientId: '952069462495-64s3mm7jambqaqv9ma37enjmgbec99p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwKcP6IxUseG1LXyqnxZFTpGz04RBB-r4',
    appId: '1:952069462495:ios:6cb9678d35c95c43bb8c6a',
    messagingSenderId: '952069462495',
    projectId: 'truecross-55cca',
    storageBucket: 'truecross-55cca.appspot.com',
    iosClientId: '952069462495-dm5ekm5u254kp6crobkfrmkmtlkl1g9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirestore.RunnerTests',
  );

}
